package com.vminhoto.chirp.service

import com.vminhoto.chirp.api.dto.ChatMessageDto
import com.vminhoto.chirp.api.mappers.toChatMessageDto
import com.vminhoto.chirp.domain.event.MessageDeletedEvent
import com.vminhoto.chirp.domain.events.chat.ChatEvent
import com.vminhoto.chirp.domain.exception.ChatNotFoundException
import com.vminhoto.chirp.domain.exception.ChatParticipantNotFoundException
import com.vminhoto.chirp.domain.exception.MessageNotFoundException
import com.vminhoto.chirp.domain.exceptions.ForbiddenException
import com.vminhoto.chirp.domain.models.ChatMessage
import com.vminhoto.chirp.domain.type.ChatId
import com.vminhoto.chirp.domain.type.ChatMessageId
import com.vminhoto.chirp.domain.type.UserId
import com.vminhoto.chirp.infra.database.entities.ChatMessageEntity
import com.vminhoto.chirp.infra.database.mappers.toChatMessage
import com.vminhoto.chirp.infra.database.repositories.ChatMessageRepository
import com.vminhoto.chirp.infra.database.repositories.ChatParticipantRepository
import com.vminhoto.chirp.infra.database.repositories.ChatRepository
import com.vminhoto.chirp.infra.message_queue.EventPublisher
import org.springframework.cache.annotation.CacheEvict
import org.springframework.context.ApplicationEventPublisher
import org.springframework.data.domain.PageRequest
import org.springframework.data.repository.findByIdOrNull
import org.springframework.stereotype.Service
import org.springframework.transaction.annotation.Transactional
import java.time.Instant

/**
 * Service related to Messages Operations and interactions with Chat Repositories.
 * @param chatRepository
 * @param chatMessageRepository
 * @param chatParticipantRepository
 * @param applicationEventPublisher
 * @param eventPublisher
 */
@Service
class ChatMessageService(
    private val chatRepository: ChatRepository,
    private val chatMessageRepository: ChatMessageRepository,
    private val chatParticipantRepository: ChatParticipantRepository,
    private val applicationEventPublisher: ApplicationEventPublisher,
    private val eventPublisher: EventPublisher
) {

    /**
     * Function to send Messages. Verifies if chat and sender exists in the database. Also fires an event through RabbitMQ
     * @param chatId Id of the chat.
     * @param senderId Id of the sender of the message.
     * @param content Content of the message.
     * @param messageId Id of the message (generated by the client).
     * @return a [ChatMessage] domain model of the result message.
     * @throws ChatNotFoundException if the chat does not exist.
     * @throws ChatParticipantNotFoundException if the Chat Participant does not exist.
     */
    @Transactional
    @CacheEvict(
        cacheNames = ["messages"],
        key = "#chatId",
    )
    fun sendMessage(
        chatId: ChatId,
        senderId: UserId,
        content: String,
        messageId: ChatMessageId? = null
    ): ChatMessage {
        val chat = chatRepository.findChatBy(chatId, senderId)
            ?: throw ChatNotFoundException()
        val sender = chatParticipantRepository.findByIdOrNull(senderId)
            ?: throw ChatParticipantNotFoundException(senderId)

        // The id is generated by the client so it can track when it receives the broadcast back if message was sent
        // and to filter its own message.
        val savedMessage = chatMessageRepository.saveAndFlush(
            ChatMessageEntity(
                id = messageId,
                content = content.trim(),
                chatId = chatId,
                chat = chat,
                sender = sender
            )
        )

        eventPublisher.publish(
            ChatEvent.NewMessage(
                senderId = sender.userId,
                senderUsername = sender.username,
                recipientIds = chat.participants.map { it.userId }.toSet(),
                chatId = chatId,
                message = savedMessage.content
            )
        )

        return savedMessage.toChatMessage()
    }

    /**
     * Function to delete a message. Verifies if the message exists and if the user is the sender. Also fires an event
     * through the application event mechanism.
     * @param messageId Id of the message
     * @param requestUserId Id of the user that requests the message deletion.
     * @throws MessageNotFoundException if the message does not exist.
     * @throws ForbiddenException if the user is not the sender of the message.
     */
    @Transactional
    fun deleteMessage(
        messageId: ChatMessageId,
        requestUserId: UserId
    ) {
        // Check if Message exists.
        val message = chatMessageRepository.findByIdOrNull(messageId)
            ?: throw MessageNotFoundException(messageId)

        // Checks if user is the sender.
        if(message.sender.userId != requestUserId) {
            throw ForbiddenException()
        }

        chatMessageRepository.delete(message)

        // Use application Event to publish a Message Deleted event. Can be consumed by the websocket mechanism.
        applicationEventPublisher.publishEvent(
            MessageDeletedEvent(
                chatId = message.chatId,
                messageId = messageId
            )
        )

        evictMessagesCache(message.chatId) //Function called only to trigger Cache Evict.
    }
    @CacheEvict(
        cacheNames = ["messages"],
        key = "#chatId",
    )
    fun evictMessagesCache(chatId: ChatId) {
        // NO-OP: Let Spring handle the cache evict
    }
}