spring:
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.mailgun.org
    username: chirpdevtest@sandbox605ed02b68f44f239255ebd2d5a4ef24.mailgun.org

jwt:
  expiration-minutes: 1000

nginx:
  require-proxy: false

chirp:
  email:
    url: "http://localhost:8080"
  rate-limit:
    ip:
      apply-limit: true
  web-socket:
    allowed-origin: "http://localhost:8080"

logging:
  level:
    com.vminhoto.chirp: DEBUG