package com.vminhoto.chirp.infra.database.repositories

import com.vminhoto.chirp.domain.type.UserId
import com.vminhoto.chirp.infra.database.entities.ChatParticipantEntity
import org.springframework.data.jpa.repository.JpaRepository
import org.springframework.data.jpa.repository.Query

/**
 * Repository interface for Chat participants
 */
interface ChatParticipantRepository: JpaRepository<ChatParticipantEntity, UserId> {

    /**
     * Function that has a autogenerated Query to find on or multiple [ChatParticipantEntity] by [UserId]
     * @param userIds Set of [UserId] to search for
     * @return Set<ChatParticipantEntity> Set of ChatParticipantEntities
     */
    fun findByUserIdIn(userIds: Set<UserId>): Set<ChatParticipantEntity>

    /**
     * Function to query our database for a [ChatParticipantEntity] by email or username
     * @param query The email or username.
     * @return [ChatParticipantEntity] if it exists.
     */
    @Query("""
        SELECT p
        FROM ChatParticipantEntity p
        WHERE LOWER(p.username) = :query OR LOWER(p.email) = :query
    """)
    fun findByEmailOrUsername(query: String): ChatParticipantEntity?
}